spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: authentication
            uri: http://localhost:8081
            predicates:
              - Path=/authentication/**
            filters:
              - StripPrefix=1
          - id: writings
            uri: http://localhost:8082
            predicates:
              - Path=/writings/**
            filters:
              - StripPrefix=1
    compatibility-verifier:
      enabled: false

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always